### ISSUE TITLE
Can't run tests if project is in a symlinked path

### ISSUE THREAD

**Issue by vinhlam** [BladeRunnerJS/brjs#1384] opened 2015-05-12 15:52 UTC
When I try to run `brjs test` from a path that contains a symlink, I get the following exception

    Testing ....../tests/test-unit (UTs):
    Unexpected Exception:
    java.lang.RuntimeException: Unable to find test pack which represents the path /...actual_full_path...../tests/test-unit/js-test-driver
    	at     com.caplin.cutlass.command.test.testrunner.JsTestDriverBundleCreator.createRequiredBundles(JsTestDriverBundleCreator.java:50)

eg.

The actual path is  `~/Documents/development/myapp`

I have a symlink in `~` created using `ln -s ~/Documents/development/myapp`
and running  `brjs test` in `~/myapp`

**Comment by ioanalianabalas** [comment] 2015-05-19 08:55
Hi @vinhlam,

I am closing this issue because it appears to be a duplicate of #1342.

**Comment by ioanalianabalas** [comment] 2015-05-19 09:03
Based on the recent comment received in the other issue, reopening this because it does not seem to be a duplicate after all.

**Comment by ioanalianabalas** [comment] 2015-05-28 11:30
Fixed by #1405.

**Comment by thanhc** [comment] 2015-06-10 13:44
This appears to already have been fixed by #1386 so closing this ticket

**Comment by andyberry88** [comment] 2015-07-21 09:45
I'm still getting this when running tests in CT using BRJS 1.0.1.

**Closed** 2015-09-11 10:55 UTC
Labels: 6 - Done, bug
