### ISSUE TITLE
[bug] Tests sometimes fail due to a Java exception

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1370] opened 2015-05-05 13:42 UTC
Sometimes, randomly, my test will fail with this exception:

```
Testing myapp\some-thing\tests\test-unit (UTs):
Unexpected Exception:
java.io.IOException: Unable to create an empty bundle file at d:\solutions\st\apps\myapp\some-thing\tests\test-unit\js-test-driver\bundles\i18n\en_i18n.bundle
        at com.caplin.cutlass.command.test.testrunner.BundlerHandler.repeatedlyAttemptToCreateBundleFile(BundlerHandler.java:86)
        at com.caplin.cutlass.command.test.testrunner.BundlerHandler.createBundleFile(BundlerHandler.java:59)
        at com.caplin.cutlass.command.test.testrunner.JsTestDriverBundleCreator.createRequiredBundles(JsTestDriverBundleCreator.java:63)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runTest(TestRunner.java:370)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runTestAndRecordDuration(TestRunner.java:357)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runAllTestsInDirectory(TestRunner.java:328)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runAllTestsInDirectory(TestRunner.java:333)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runAllTestsInDirectory(TestRunner.java:333)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runAllTestsInDirectory(TestRunner.java:333)
        at com.caplin.cutlass.command.test.testrunner.TestRunner.runTests(TestRunner.java:164)
        at com.caplin.cutlass.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:118)
        at com.caplin.cutlass.command.test.TestCommand.doCommand(TestCommand.java:55)
        at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
        at org.bladerunnerjs.model.BRJS.runCommand(BRJS.java:373)
        at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:34)
        at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)
        at org.bladerunnerjs.model.BRJS.runUserCommand(BRJS.java:378)
        at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:111)
        at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:63)
```

I've seen it happen in libs & blades. Running the same test again right after works fine (usually).

This is on Windows7 with Java 1.7.0_55 and BRJS v0.15.4.0-gbd82eac

**Comment by ioanalianabalas** [comment] 2015-06-12 14:47
Hi @janhancic I am not able to replicate this issue and nobody else has ever seen this before either, so we will be moving it in the backlog for now. Please let us know if you can think of a way in which we can reliably replicate it.

**Comment by janhancic** [comment] 2015-06-12 14:51
I can't think of any. But it does seem worrying that there are this many issues that only happen on some computers, and none of the BRJS team members can ever reproduce them. I think we should be having a wider conversation about that and try to figure out how to solve this, as everybody is wasting a lot of time.

Thoughts @dchambers @andyberry88 ?

**Comment by dchambers** [comment] 2015-06-12 15:08
AFAIK, both of the file locking issues (this one and #446) affect you, and you only. Certainly, nobody else has raised any issues like this that I am aware of. In all likelihood both of them are caused by a conflict with some other process on your machine.

If this was happening to other Windows users I'd guess it was either the Windows file indexing service or a virus checker, but since it only happens to you I imagine you have some other background process running on your machine that likes to scan all files on the entire computer. We've asked before, of course, but you're not aware of any such process.

So, realistically, since none of us in the team can replicate (including our 3 Windows users) and a static inspection of the code in the past did not reveal anything, there's not much we can do with this without more to go on.

The only thing I could think of without more info, and this is incredibly speculative, is that we could write or find a program that randomly opens and closes files for reading. The problem with this is that even having a `read` lock on a file that we are attempting to write to will cause errors which are not actual bugs in our code, and so it's not clear how much we'd learn from this, or how much time we'd spend debugging non issues.

**Comment by dchambers** [comment] 2015-06-12 15:10
On the other hand, if we could at least identify the background process that is causing this problem, then we could start to understand the true nature of the problem, and what should be done.

**Comment by janhancic** [comment] 2015-06-12 15:22
There were other problems that were affecting other people (Brian, NESS guys) too, but strangely not the BRJS team :) The bug where you couldn't run tests from the SDK folder springs to mind as an example.

So while there might very well be a process that is causing this issues it is most certainly not only on my machine. That's why I'm saying we should do something about this and try to identify what's the difference between my machine and @ioanalianabalas 's for example. Currently BRJS is being developed in an environment(s) that isn't anything like the environment(s) where it's used it seems, and that seems like a major flaw in our dev process.

**Comment by dchambers** [comment] 2015-06-12 15:35
> There were other problems that were affecting other people (Brian, NESS guys) too, but strangely not the BRJS team :) The bug where you couldn't run tests from the SDK folder springs to mind as an example.

@janhancic, are you saying that Brian and NESS are seeing this issue too? If so then we could get each person that sees it to print the list of all processes on their machines, filter down to the common processes on _our_ and _your_ machines, and then diff the lists. Otherwise, to fix this bug we need a chance of replicating it.

Alternatively, we could speculatively assume that it's because we don't defensively handle `read` locks when writing files, and mediate all writing through a utility that retries writes, etc, etc. My problem with that is that we could then just as easily find out that it wasn't the problem after all.

If it's only happening on your machine then my suggestion would be to try disabling the Windows file service and virus checker for a bit and see if that fixes it. If it doesn't then any other background processes you can think of that might possibly cause this?

**Comment by dchambers** [comment] 2015-06-12 15:49
Actually, I just remembered that @ioanalianabalas told me that we already have code that keeps retrying the write for a while when this exception happens, which you can see from the `repeatedlyAttemptToCreateBundleFile` method in the call-stack. Given that the call-stack also mentions which file it is that it can't write (`d:\solutions\st\apps\myapp\some-thing\tests\test-unit\js-test-driver\bundles\i18n\en_i18n.bundle` in the call-stack above), you could just see which process has the lock the next time it happens.

Since it sounds like it's a long held lock, my guess would therefore be that it's a separate BRJS process you have running somewhere, but you can let us know when you next see it.

**Comment by janhancic** [comment] 2015-06-12 16:10
Can we take a step back and not focus solely on this one issue? I'm talking about a general problem that encompasses many different bugs (not all of them to do with file locking) that seem to only happen to people not working on BRJS.

I propose we have a chat on Monday and see how we can solve this problem.

**Comment by janhancic** [comment] 2015-06-12 16:14
But just for the sake of completeness:

- yes, other people are having the same problems, it just happens that I'm the only one reporting them
- with every single file-locking related bug, there wasn't anything else holding on to files other than BRJS, we went trough this many times and I have proven it so on various occasions
- yes, let's compile a list of processes to see if there is anything strange on my machine

**Comment by dchambers** [comment] 2015-06-12 22:29
> * with every single file-locking related bug, there wasn't anything else holding on to files other than BRJS, we went trough this many times and I have proven it so on various occasions.

In that case, if another instance of BRJS is holding onto a file lock for a bundle created for testing, then this should only really be possible if you run your tests through the dashboard via `brjs serve`, since all other BRJS commands are short lived.

Therefore, my guess now that this problem is caused by a buggy terminal you are using that is causing processes to remain open when they shouldn't be. Back when I used to run Windows, I found that all off the third-party terminals were buggy in one way or another. And, as far as I'm aware, none of the BRJS team use third party Window terminals &mdash; only Git Bash is used for when a UNIX terminal is needed I believe.

Can you please let me know what terminal you are using, and we'll see if we can replicate this. Additionally, can you let me know if the problems stop if you instead use Windows Command Prompt to run all your `brjs` commands.

**Comment by dchambers** [comment] 2015-06-15 09:06
After speaking with @janhancic this morning, we came up with a number of potential differences between the environments used by members of the BRJS & Motif teams:

  1. Larger app
  1. GitBash terminal.

Plus we came up with some potential hypotheses for why this might be happening:

  1. ~~Running tests via dashboard, which would be part of a long running `brjs serve` command~~ (I've confirmed that @janhancic never runs tests this way).
  1. ~~Background processes that happen to read all files like indexing services and virus checkers~~ (The call-stack shows that we are trying the write operation multiple times, so it's not a transient file lock, plus we are using the same virus checker and indexing service as the Motif teams are).
  1. Orphaned test process (perhaps either BRJS of JsTestDriver itself create orphaned child test processes that don't sometimes become zombie processes, never dying, and so keeping there file locks open).
  1. ~~`brjs test-server` + `brjs test` interaction~~ (@janhancic has informed that he sees this even when he uses `brjs test` by itself).
  1. Race condition in the threaded (mainly model acquisition) part of the code, that may be activated by the larger app size.
  1. ~~Non-determinism caused by Java 8's non-deterministic map ordering~~ (I've confirmed that @janhancic is using Java 7 as his default Java version).
  1. JsTestDriver synchronization race condition, caused by some synchronization issue between the two processes.
  1. GitBash orphaning command processes (don't know how this could even work, but something like this might be possible given that the team don't tend to use GitBash for executing BRJS commands).

**Note:** while the most obvious explanation would just be that we are opening the same file twice, the fact this only happens occasionally means that a race-condition, non-determinism or global-state change would also be required to make that possible, hence the more detailed explanations above.

**Comment by dchambers** [comment] 2015-06-15 09:31
We should look at 5, 9, 10 & 13 first, since they are quick to check. Plus, we need to verify they are using a grunt command. Subsequently, we should opportunistically fix 11, 12 & 14 since they could all be improved.

**Comment by dchambers** [comment] 2015-06-15 09:56
Just spoke to @janhancic, it's a background gulp task rather than a grunt task, but same difference. @thanhc / @thecapdan: we should probably re-test this using their app again, but this time with the gulp task running in the background.

**Comment by thecapdan** [comment] 2015-06-15 10:18
One virus scanner setting that might be different, for those with ESET

Open up your antivirus from the taskbar
Click "Setup"
Click "Antivirus and Antispyware protection"
Under "Web access protection", click configure
In the window that just popped up, click "HTTP,HTTPS" under "Web access protection"
"Enable HTTP checking" <- @janhancic had it checked, i had it unchecked

**Comment by dchambers** [comment] 2015-06-15 10:21
> "Enable HTTP checking" <- @janhancic had it checked, i had it unchecked

Interesting, we've noticed problems with this in the past, and have always advised people to disable that setting. @janhancic, can you please update your setting to match?

**Comment by andyberry88** [comment] 2015-06-15 13:08
#1427 fixes issues `#11`, `#12` and `#14`. It also addresses some of `#13` since we were using `MemoizedFile` in places when creating the bundle files which may have been causing problems.

**Comment by mikes-c** [comment] 2015-08-26 09:35
@janhancic , did you update your setting to match?

Assuming you did.  Have you experienced this issue again since updating the setting?

**Comment by janhancic** [comment] 2015-08-26 09:38
Don't remember if I did. And I'm using a mac now so I no longer have this issue.

**Comment by thecapdan** [comment] 2016-02-03 08:45
Will close this for now as it has not been reported for a while.

**Closed by thecapdan** 2016-02-03 08:45 UTC
Labels: 1 - Planned, bug
