### ISSUE TITLE
Failing to run closure compiler tasks via Grunt

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1168] opened 2015-01-12 10:59 UTC
When building a war file through the grunt shell, bladerunner when running the following command:
    brjs build-app sdp ..\ -w

Note, when run on any command prompt (msysgit/cygwin/dos) it passes. Suspect that BRJS cannot cope with outputting closure compiler warnings when run through grunt-shell and closes without displaying any error messages.

More information including debug output can be found here: http://yourls.caplin.com/8

**Comment by lukeapage** [comment] 2015-01-12 14:55
as stressed in the caplin issue, I understand it might be a problem with my setup, but it would be good that if brjs gets an unhandled exception, some information about it is logged so we have an idea what is going on.

**Comment by ioanalianabalas** [comment] 2015-01-23 15:38
@lukeapage, I was unable to reproduce this issue in the latest version of BRJS. Could you please tell us what version you are using?

I have used this script to generate the war file: 

    module.exports = function(grunt) {
        grunt.loadNpmTasks('grunt-shell');
        grunt.initConfig({
            shell: {
                buildApp: {
                    command: 'brjs build-app exampleApp ./.. -w'
                }
            }
        });
        grunt.registerTask('default', ['shell:buildApp']);
    }

This has successfully created my war file.

I have also tried introducing a closure compiler error and that was outputted correctly by Grunt.

**Comment by lukeapage** [comment] 2015-01-23 17:08
I am updating to the latest grunt-shell - I can retry with that in 2 weeks. am not working next week.

**Comment by ioanalianabalas** [comment] 2015-01-26 09:43
@lukeapage no problem at all. Let us know when you have an update.

**Comment by ioanalianabalas** [comment] 2015-02-18 09:35
@lukeapage, I was wondering if you have had the chance to re-test this? Thank you.

**Comment by lukeapage** [comment] 2015-02-19 08:59
@ioanalianabalas @tobycatlin I've upgraded grunt-shell and the problem no longer occurs. You can close this issue and the related Jira.

**Comment by ioanalianabalas** [comment] 2015-02-19 09:40
@lukeapage, no problem at all - glad to hear it is working for you.

**Closed** 2015-02-19 09:41 UTC
Labels: 1 - Planned, CaplinSupport
