### ISSUE TITLE
Allow shallow directory structures in workbench source code

### ISSUE THREAD

**Issue by james-s-turner** [BladeRunnerJS/brjs#1227] opened 2015-02-18 09:44 UTC
IF I want to add source code to my workbench in the `src` directory I have to create a directory structure that mirrors the blades namespace. We got rid of this requirement for normal blades code.We should do the  same for workbench code.

**Comment by andyberry88** [comment] 2015-02-18 09:58
> I have to create a directory structure that mirrors the blades namespace

This is because workbenches can (or should) be able to define classes within any the app namespace. So the implied namespace for a Workbench is `<app-prefix>` rather than `<app-prefix>/<bladeset>/<blade>`. Looking at it now this does seem confusing, maybe we should revisit whether Workbenches should be able to define classes outwith the Blade namespace.

@james-s-turner can you try removing all directories can requiring the Workbench class via `<app-prefix>/<ClassName>`?

**Comment by james-s-turner** [comment] 2015-02-18 10:20
Yes that works with just the app prefix. It does seem confusing. Why would you want to reference classes  anywhere in the app namespace? Does that mean workbenches can share `src` code. In which case we have coupled blades :-(

**Comment by andyberry88** [comment] 2015-02-18 10:32
> Why would you want to reference classes anywhere in the app namespace?

It's so that Workbenches can define properties etc. (i18n, css, xml config) in any namespace to make them behave more like the app. There is no code sharing at all between Workbenches.

**Comment by james-s-turner** [comment] 2015-02-18 11:21
Yes - I know about inheriting that stuff ! But you shouldn't be able to reference JavaScript in the Aspect

**Comment by janhancic** [comment] 2015-02-18 14:05
Duplicate of this: https://github.com/BladeRunnerJS/brjs/issues/1155

**Comment by andyberry88** [comment] 2015-03-03 16:53
Closing as a duplicate of #1155.

**Closed by andyberry88** 2015-03-03 16:53 UTC
