### ISSUE TITLE
Synchronous XMLHttpRequest on main thread deprecated

### ISSUE THREAD

**Issue by oniseijin** [BladeRunnerJS/brjs#1651] opened 2016-02-02 07:14 UTC
On BRJS Angular TODO MVC example, the following warning is given in File.js line 19

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/

<pre>
/**
* Read a contents from a URL
*
* @param {String} url The URL to load contents from
*/
exports.readFileSync = function(url) {
	var xhr = new XMLHttpRequest();
	xhr.open('GET', url, false); // LINE 19, problem here
	xhr.send();
	if (xhr.status === HTTP_OK) {
		return xhr.responseText;
	} else {
		throw new Errors.RequestFailedError("Unable to load file " + url + " (status " + xhr.status + ").");
	}
};

});
</pre>

Fully functional, but a sign of some actions likely necessary

**Comment by dchambers** [comment] 2016-02-02 07:57
Hi @oniseijin, thanks for reporting. I'm going to close this issue though because it's a duplicate of #1276.

**Closed by dchambers** 2016-02-02 07:57 UTC

**Comment by oniseijin** [comment] 2016-02-02 10:15
Ahh, okay. Sorry, did a seatch and could not find a reference of it before

**Comment by dchambers** [comment] 2016-02-02 11:41
No probs.
