### ISSUE TITLE
Document SinglePassFormatter and how parsers are meant to be used

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1183] opened 2015-01-21 11:53 UTC
Individual parsers that can handle their own return value can cause an infinite loop. Our use cause is that we have a date parser, which is given a local date and parses it to a GMT date based on the current timezone (e.g. subtract an hour when the timezone is GMT+1).

The EditableProperty will reset the parser loop once this value is parsed, and then feed the new value back into the parser. The parser will simply apply the adjustment again to the new date, resulting in a new value again. This can go on indefinitely unless there is some limiting value.
Combinations of parsers that can handle each others' input can cause similar behaviour. Our case here is a local number parser that accepts a localised number string (e.g. '9.000,1') and attempts to parse it to a JavaScript number, and a minimum decimals parser that accepts a number and appends trailing zeroes, returning a string to by necessity.

So, the local number parser may be given '900,1', which is nine hundred point one in locales where ',' is a decimal delimiter. It will then return 900.1 as a number. When the loop is reset, it ignores this value (recognising that it's already a number). Then the minimum decimals parser will append trailing zeroes, returning '900.1000'. When the loop is reset again, the local number parser assumes the '.' is a thousands delimiter, and returns 9001000, which the decimals parser can append trailing zeroes to again. This continues until we get Infinity returned, but could cause an infinite loop in cases where there is no limiting value.

**Comment by minlokchan** [comment] 2015-01-21 13:49
Internal Reference: http://yourls.caplin.com/b

**Comment by dchambers** [comment] 2015-01-21 14:25
Hi @tobycatlin,

This issue comes up at least once a year, and is caused by a communication failure on our part which we should seek to address. I've just checked, and the current `Parser` interface in BRJS provides [no guidance whatsover](https://github.com/BladeRunnerJS/brjs/blob/v0.14.3/brjs-sdk/workspace/sdk/libs/javascript/br-presenter/src/br/presenter/parser/Parser.js) as to how parsers are meant to be used. The old interface within CT used to talk about the similarities to the _production-rules_ in [formal grammars](http://en.wikipedia.org/wiki/Formal_grammar), but that probably did more to confuse people than anything else.

> Individual parsers that can handle their own return value can cause an infinite loop. Our use cause is that we have a date parser, which is given a local date and parses it to a GMT date based on the current timezone (e.g. subtract an hour when the timezone is GMT+1).

The long and short of it is that parsers are designed to be run repeatedly so that complex expressions like `9 + (5 + (2 * 3))` could be reduced to `20` using just a single parser, and that parsers should produce output that is closer to _normalized-form_ than the input they receive.

In the use case you describe, the parsers output is no closer to being in _normal-form_ than the input it receives. Worse still, the parser is unable to unambigously differentiate local time from GMT, so that if a user entered a GMT time it would then be converted to some other time-zone, even if parsers weren't repeatedly applied. Both of these problems could be fixed by displaying the time-zone in normalized form, for example `13:00 GMT`.

Here's how parsing might then work:

  * `14:00` -> `13:00 GMT`
  * `13:00 GMT` -> `13:00 GMT`
  * `14:00 CET` -> `14:00 CET` (if you decided to allow users to keep times displayed in the time-zone of their choice)

> So, the local number parser may be given '900,1', which is nine hundred point one in locales where ',' is a decimal delimiter. It will then return 900.1 as a number. When the loop is reset, it ignores this value (recognising that it's already a number). Then the minimum decimals parser will append trailing zeroes, returning '900.1000'. When the loop is reset again, the local number parser assumes the '.' is a thousands delimiter, and returns 9001000, which the decimals parser can append trailing zeroes to again. This continues until we get Infinity returned, but could cause an infinite loop in cases where there is no limiting value.

In this case, surely converting from the users' desired locale to another locale is bad from a user satisfaction perspective. The fact that the European and British/American numbering systems produce numbers that are often impossible to disambiguate is even further reason not to do that. You will often see the same type of problem with US and UK dates, where users are left scratching their heads trying to guess what they are meant to be looking at.

**Comment by dchambers** [comment] 2015-01-29 13:31
Okay, here's my suggestion for the interface documentation:

> Parsers allow you to convert arbitrary user-input into some normalized form, and so provide additional flexibility to the end-user as to how data entry is performed. Parsers can be designed to work in co-operation with each other, allowing complex user input to be normalized using a series of progressive transformations.

> For example, the input `-(3 + (4 * 5) + 2)` could be normalized to `-25` via the following steps:

>   1. `-(3 + (4 * 5) + 2)` -> `-(3 + (20) + 2)` (_operator-parser_)
>   1. `-(3 + (20) + 2)` -> `-(3 + 20 + 2)` (_bracket-parser_)
>   1. `-(3 + 20 + 2)` -> `-(23 + 2)` (_operator-parser_)
>   1. `-(23 + 2)` -> `-(25)` (_operator-parser_)
>   1. `-(25)` -> `-25` (_bracket-parser_)

> Notice here how the input is slowly transformed into it's a final value by repeatedly applying a couple of simple parser transformations, and that parsing only stops when none of the parsers are able to further simplify the input text.

> For this to work, parsers must obey the following two rules:

>   1. A parser's output must be closer to normal form than it's input.
>   1. Parsers must be able to disambiguate the meaning of the text they are parsing (e.g. whether '12/01/2000' is the UK date "12th of January, 2000" or the US date "December the 1st, 2000"?).

**Comment by ioanalianabalas** [comment] 2015-04-15 11:10
Fixed by #1344, where I have added the documentation suggested by @dchambers.

**Closed** 2015-04-30 09:51 UTC
Labels: CaplinSupport, docs
