### ISSUE TITLE
Ocassional exceptions while using BRJS

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1552] opened 2015-10-01 13:03 UTC
Clients occasionally see stack traces involving circular-dependency graph creation, like this:

```
java.lang.NullPointerException
	at org.bladerunnerjs.utility.NonCircularTransitivePreExportDependencyGraphCreator.reachable(NonCircularTransitivePreExportDependencyGraphCreator.java:49)
	at org.bladerunnerjs.utility.NonCircularTransitivePreExportDependencyGraphCreator.nonCircularPostExportDependencies(NonCircularTransitivePreExportDependencyGraphCreator.java:37)
	at org.bladerunnerjs.utility.NonCircularTransitivePreExportDependencyGraphCreator.createGraph(NonCircularTransitivePreExportDependencyGraphCreator.java:24)
	at org.bladerunnerjs.utility.SourceModuleDependencyOrderCalculator.getOrderedSourceModules(SourceModuleDependencyOrderCalculator.java:17)
	at org.bladerunnerjs.utility.BundleSetBuilder.createBundleSet(BundleSetBuilder.java:65)
	at org.bladerunnerjs.model.BundleSetCreator.createBundleSet(BundleSetCreator.java:50)
	at org.bladerunnerjs.model.AbstractBundlableNode.lambda$getBundleSet$2(AbstractBundlableNode.java:91)
	at org.bladerunnerjs.model.AbstractBundlableNode$$Lambda$1.get(Unknown Source)
	at org.bladerunnerjs.api.memoization.MemoizedValue.value(MemoizedValue.java:88)
	at org.bladerunnerjs.model.AbstractBundlableNode.getBundleSet(AbstractBundlableNode.java:90)
	at org.bladerunnerjs.model.AbstractBrowsableNode.filterIndexPage(AbstractBrowsableNode.java:24)
	at org.bladerunnerjs.utility.AppRequestHandler.getIndexPageContent(AppRequestHandler.java:215)
	at org.bladerunnerjs.utility.AppRequestHandler.handleLogicalRequest(AppRequestHandler.java:114)
	at org.bladerunnerjs.appserver.BRJSDevServlet.doGet(BRJSDevServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1317)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:83)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:69)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:43)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:574)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:293)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:120)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:69)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:43)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:532)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

I've had a look at the related code, and have the following hypothesis:

  1. We have a `combinedDefineTimeDependencyGraph` map that contains the combined list of _pre-export_ and _post-export_ _define-time_ dependencies, but only for source modules that appear as _pre-export_ dependencies somewhere.
  1. We iterate the list of all _post-export_ dependencies, and ask whether they are _reachable_, which involves iterating the combined _define-time_ dependencies for that source module, which might not be there if that source module never appears as a _pre-export_ dependency.

The fix for this would appear to be to iterate the union of _pre-export_ and _post-export_ dependencies at line 17 of `NonCircularTransitivePreExportDependencyGraphCreator`.

**Comment by andyberry88** [comment] 2015-10-01 13:58
This is a duplicate of https://github.com/BladeRunnerJS/brjs/issues/1517. Closing this issue and I'll add the description above to #1517.

**Closed by andyberry88** 2015-10-01 13:58 UTC
Labels: 0 - Backlog, bug
