### ISSUE TITLE
JS bundler fails to encode non ascii characters

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1181] opened 2015-01-19 16:23 UTC
momentjs has some non utf-8 strings included as part of its definitions

However when I build the app with closure-simple compression we get this output:
"L\ufffd"
However \ufffd is not the right encoding for Lø- 
it should be 
"L\u00f8".

I suspect a bug has been introduced in the closure minifier where closure is told the wrong encoding of the data being passed

See http://yourls.caplin.com/a for the internal issue.

**Comment by lukeapage** [comment] 2015-01-19 16:41
"momentjs has some non utf-8 strings included as part of its definitions"

should be 

momentjs has some non ascii strings included as part of its definitions

We need a fix or work-around (where the work-around is preferably not to remove minification) before we can release this cycle, which is planned for 4 weeks time.

**Comment by andyberry88** [comment] 2015-01-19 16:43
@lukeapage are you using vanilla open source BRJS or BRJS included inside CT?

**Comment by lukeapage** [comment] 2015-01-19 16:59
BRJS inside CT.

If the fix is in the closure compiler part, would we be able to take just that jar and replace it in the classpath?

**Comment by andyberry88** [comment] 2015-01-19 17:02
Yes, my plan is to make the fix on top of the 0.14.3 codebase and release a BRJS v0.14.4. Since CT was released with v0.14.3 it should be a case of just replacing the jar(s). I'll have a chat with the CT team since they may choose to just release a new version of CT anyway.

**Comment by lukeapage** [comment] 2015-01-20 08:13
thanks. Let me know how the timescales develop - I have thought of a work-around, which is to use combine, unpack the war, use uglify to minify the js and then re-pack the war - not ideal, but not that much work either if you can't fix this in time.

**Comment by andyberry88** [comment] 2015-01-20 12:06
Hi @lukeapage,

I'm unable to reproduce this in BRJS. I've added the same character you're using to a vanilla BRJS app and see the same character in the browser & see it encoded correctly (as `\u00f8`) in the minified bundle. Can I get you to try the same thing, or try using an alert to display the same character? I suspect this might be an issue in a CT library where it doesn't handle encoded characters correctly when rendering to the browser.


![screen shot 2015-01-20 at 11 47 38](https://cloud.githubusercontent.com/assets/726896/5816799/7d507080-a09c-11e4-8ed4-31511420be9f.png)
![screen shot 2015-01-20 at 11 47 51](https://cloud.githubusercontent.com/assets/726896/5816798/7d4ff948-a09c-11e4-876c-4bc5d4931cd2.png)
![screen shot 2015-01-20 at 11 48 11](https://cloud.githubusercontent.com/assets/726896/5816800/7dbd2bb2-a09c-11e4-9e55-99e20b1bcf85.png)

**Comment by lukeapage** [comment] 2015-01-20 12:15
Hi,

The only obvious difference is that we use closure-simple and you are using closure-whitespace.

It definitely is brjs - The reason I said it became "L\ufffd" was that I looked at the result of the bundle. Of course it could be a result of something else in caplin trader or the libs that is causing closure to think it is a different character encoding, will have to test.

This is the actual file causing us problems (a later and larger version than what we have)  - http://momentjs.com/downloads/moment-with-locales.js

**Comment by andyberry88** [comment] 2015-01-20 12:23
> It definitely is brjs - The reason I said it became "L\ufffd" was that I looked at the result of the bundle. Of course it could be a result of something else in caplin trader or the libs that is causing closure to think it is a different character encoding, will have to test.

Yep ok, if it's wrong in the bundle it's definitely an issue with BRJS. As far as I know there isn't any kind of content filtering in CT, but I could be wrong.

> The only obvious difference is that we use closure-simple and you are using closure-whitespace.

I tried using both whitespace and simple, no problem with either. I did however test this by changing the `dev` minification setting which suggests it may be an issue in the `build-app` command rather than the minifier. I'll get back to you on that.

**Comment by lukeapage** [comment] 2015-01-20 12:28
So, I reproduced in a test app.

1. create a new app with brjs
2. Change the App.js Hello World string to have `return "hello world!" + "Sø_Ma_Ti_On_To_Fr_Lø";`
3. change the index.html bundle to `<@js.bundle dev-minifier="none" prod-minifier="closure-simple"@/>`
4. build the app `brjs test ../ -w`
5. Open the war file and look at the compiled bundle file.. see
```js
....e.getHello=function(){return"hello world!S\ufffd_Ma_Ti_On_To_Fr_L\ufffd"};e.logHello=function(){console....
```

**Comment by andyberry88** [comment] 2015-01-20 13:30
I've managed to track down the issue. It is an issue in the minifier plugin as you first suggested and something that only happens on Windows which is why it was proving so difficult for me to reproduce on a Mac.
It's a very small fix so we should have a v0.14.4 release for you within the next couple of days.

**Comment by lukeapage** [comment] 2015-01-20 13:54
Thanks!

**Comment by andyberry88** [comment] 2015-01-20 14:32
Fixed by https://github.com/BladeRunnerJS/brjs/pull/1182

**Comment by thecapdan** [comment] 2015-01-21 12:04
Tested using lukes example, works now - correctly uses L\u00f8

**Closed** 2015-01-21 12:04 UTC
Labels: 5 - Test, bundlers, CaplinSupport, high-priority
