### ISSUE TITLE
BRJS prevents me saving/deleting files (locked files/folders)

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#446] opened 2014-03-20 13:57 UTC
I'm not 100% sure this is BRJS's fault, but because I haven't experienced the same issue before with the same workflow I'm fairly certain it is it's fault :)

If I have BRJS running (`brjs serve`) and edit and save a file I will sometimes get an error in my editor (Sublime on Win7) saying that it couldn't save the file because of permission error.
If I then hit save one more time (or twice) the error goes away and the file is saved.

@dchambers has a suspicion that BRJS is not closing down file handles properly or in time.

**Comment by dchambers** [comment] 2015-02-18 17:48
@ioanalianabalas, hope you don't mind. I've assigned this issue to you because I can't replicate, and suspect it only happens on Windows. I created a pull-request (#1233) with some code and instructions to help replicate.

**Comment by ioanalianabalas** [comment] 2015-02-19 10:39
The [xml-file-lock-reproduction-attempt branch](https://github.com/BladeRunnerJS/brjs/tree/xml-file-lock-reproduction-attempt) contains @dchambers failed attempt to replicate #446. In addition to these changes I created a new app with the namespace `appx`, and containing a single blade in the default bladeset named `myblade`.

Additionally, @dchambers added this to the app's `index.html`:

```js
require('appx/myblade/MybladeViewModel');
var XmlResourceService = require('br/services/xml/BRXmlResourceService');
(new XmlResourceService()).getXmlDocument('gridDefinitions');
```

this inside `resources/xml/gridDef1.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gridDefinitions xmlns="http://schema.caplin.com/CaplinTrader/gridDefinitions">
	<grids>
		<grid id="appx.equities.london" displayName="@{appx.layout.caption.equities.london}" baseTemplate="caplinx.fxtrader.london.equitiesGrid">
			<gridRowModel>
				<caplin.sljs-container-grid-data-provider container="/CONTAINER/EQ/London"/>
			</gridRowModel>
		</grid>
	</grids>
</gridDefinitions>
```

and this inside `blades/myblade/resources/xml/gridDef2.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gridDefinitions xmlns="http://schema.caplin.com/CaplinTrader/gridDefinitions">
	<grids>
		<grid id="appx.myblade.gridexpandable.fiALL" displayName="FI ALL" baseTemplate="appx.myblade.fiGrid">
			<gridRowModel>
				<caplin.sljs-container-grid-data-provider container="/CONTAINER/FI/ALL"/>
			</gridRowModel>
		</grid>
	</grids>
</gridDefinitions>
```

Then, with these changes made, @dchambers tried modifying both files then refreshing the page while while `brjs serve` was left running. @dchambers suspects this bug only occurs on Windows.

**Comment by dchambers** [comment] 2015-02-20 17:46
I noticed that according to the docs, the [`XMLStreamReader.close()` method](http://docs.oracle.com/javaee/5/api/javax/xml/stream/XMLStreamReader.html#close()) doesn't close the underlying  `FileReader`, so that loading apps via `brjs serve` should always lock any XML files that app depends on, and so that it should never be possible edit these files. I [committed a fix](https://github.com/BladeRunnerJS/brjs/commit/9dc5a66fbc6719483e6910ba3db8b96c3eec0902) for this, but I don't want to merge it into `develop` as I'm sceptical it will help given that @janhancic only seems to see this problem intermittently.

The only theory I could come up with to explain why @janhancic doesn't see this problem all the time is that perhaps the OS automatically releases file handles for files that are read all the way to the end, so I created a [test](https://github.com/BladeRunnerJS/brjs/commit/853d6f29acfae41ead46a0120b42bb76f513d051) to verify this, but this turned out not to be the case on Windows.

@ioanalianabalas is going to try running this test on Windows to see if it's different on Windows when she has some time.

**Comment by thanhc** [comment] 2015-04-08 13:17
Not able to reproduce the xml file locking issue, tested the supposed fix, hopefully this will stop it from happening

**Closed by thanhc** 2015-04-08 13:17 UTC
Labels: 6 - Done, bug, size 2

**Comment by janhancic** [comment] 2015-04-14 13:03
Using `v0.15.4.0-gbd82eac` this still happens. The file that is locked is a trade model XML file. I haven't made any edits to the file or anything.

**Comment by dchambers** [comment] 2015-04-14 13:08
Hi @janhancic, the change (079ffe4) that @thanhc has merged has currently only made it's way into the `develop` branch, and has not yet been released.

**Comment by janhancic** [comment] 2015-04-14 13:08
Ah OK, sorry about that, I thought it was already shipped :)
