### ISSUE TITLE
Trailing "/" in urls result in 404

### ISSUE THREAD

**Issue by MstWntd** [BladeRunnerJS/brjs#1563] opened 2015-10-19 12:51 UTC
Pre open source BRJS locale URLs without a trailing `/` automatically had it appended automatically. e.g. `myapp/en` -> `myapp/en/`. This doesn't happy any more, the URL used for locales is now `/myApp/en`, serve by the file `/myApp/en.html`. 

`myApp/en/` should either redirect to `/myApp/en` or `/myApp/en/` should be URL used to locale pages.

Internal issue: http://yourls.caplin.com/0

**Comment by mickylad** [comment] 2015-11-04 10:51
In addition to this it also seems that now a leading slash is *always* added to the language part of the URL.

This has led to our servers forwarding users to `host//en` rather than `host/en`.

Both of these URLs work and in some ways we don't mind that that `//en` now works, rather that it has effectively become the 'default' URL we present to users.

**Comment by andyberry88** [comment] 2015-11-05 16:54
In the move to BRJS and flat file deployments we opted to write out the locale index files as `myApp/en.html` rather than `myApp/en/index.html`. This results in the URL being `myApp/en` rather than `myApp/en/`. Given this new behaviour is by design it's not a bug and I don't think it's something we want to change. You can add a custom filter to automatically redirect users from a URL with a trailing `/` to one without, similar to the explanation on https://stackoverflow.com/questions/2725102/how-to-use-a-servlet-filter-in-java-to-change-an-incoming-servlet-request-url.

@mickylad the extra URL being appended is a bug that we'll look to fix. Does it look to be the same issue as https://github.com/BladeRunnerJS/brjs/issues/1487? What version of BladeRunnerJS are you seeing this with?

**Comment by mickylad** [comment] 2015-11-06 10:19
Thanks Andy. With regards to the trailing slash that's exactly what we've done - we knew it was possible you wouldn't want to change it on your side and that it might take us some time to get that change released otherwise. That solution works fine for us.

The double slash does look to be #1487 - we saw the issue after we upgraded from 6.2.2-297982 to 6.2.4-299966.

**Comment by mickylad** [comment] 2015-11-06 12:29
Whoops, just realised I've quoted Streamlink versions, sorry, will fix that.

**Comment by andyberry88** [comment] 2015-11-09 13:16
Thanks @mickylad. As it's not something we're going to change I'm going to close this issue. We'll look to fix #1487 in a following release. I can't give you an ETA on it but it's in our current focus milestone so will be one of the next things we look at.

**Closed by andyberry88** 2015-11-09 13:16 UTC
Labels: 1 - Planned, CaplinSupport, enhancement
