### ISSUE TITLE
BRJS doesn't renamespace Blades in the 'default' BladeSet

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1245] opened 2015-02-25 11:44 UTC
We have a bladeset-less blade which mainly consists of grid XML files and one JS file. The blade is a ComonJS blade.

When you export our app and import it nothing in that blade get's re-namespaced. That includes i18n tokes, grid XML files and JS files.

**Comment by janhancic** [comment] 2015-02-25 11:44
Tagging @sospirited as he found the issue.

**Comment by andyberry88** [comment] 2015-03-04 10:48
This is fixed by https://github.com/BladeRunnerJS/brjs/pull/1261

**Closed** 2015-03-05 17:17 UTC
Labels: 6 - Done, bug

**Comment by thanhc** [comment] 2015-03-05 17:23
Oddly, not able to reproduce the issue with i18n and js files not being namespaced correctly when in the default bladeset only xml causing an issue.  But re-tested the issue using the offending app and everything has been namespaced correctly.
