### ISSUE TITLE
brjs flags only works at end of command

### ISSUE THREAD

**Issue by andreoid** [BladeRunnerJS/brjs#1357] opened 2015-04-22 12:52 UTC
In our mutli-module gradle build files, I wanted to be able to change the top-level default brjs command to be "brjs --debug" rather than just "brjs".

But this is not possible as brjs --debug <command> says
"No such command --debug"
e.g.

```
brjs --debug build-app fxtrader
```

If the debug comes at the end, it works
```
brjs build-app fxtrader --debug
```
But I need to be able to set it at the start, as in my top-level gradle build file, I want all my subprojects to inherit the method to execute brjs and to all have common flags.

(The problem affects the --info flag too, and quite possibly other flags also)

**Comment by andyberry88** [comment] 2015-04-23 11:49
Hi @andreoid, this is a duplicate of #1357 so I'm going to close this issue and add it as a comment to that issue.

**Closed by andyberry88** 2015-04-23 11:49 UTC
