### ISSUE TITLE
Error parsing test runner configuration file

### ISSUE THREAD

**Issue by michalvankodev** [BladeRunnerJS/brjs#1630] opened 2016-01-04 09:30 UTC
Since new upgrade to BRJS v1.3.0 when running tests I get this error.

```
INFO: HV000001: Hibernate Validator 5.0.1.Final
The app 'salestrader' is either missing BRJS jar(s), contains BRJS jar(s) it shouldn't or the BRJS jar(s) are outdated. You should delete all jars prefixed with 'brjs-' in the WEB-INF/lib directory and copy in all jars contained in 'sdk/libs/java/application'.
Error:
  Error parsing test runner configuration file '/home/mvanko/Projects/salestrader/conf/test-runner.conf'.; null

Caused By:
  null

Stack Trace:
org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error parsing test runner configuration file '/home/mvanko/Projects/salestrader/conf/test-runner.conf'.; null
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:76)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:59)
	at org.bladerunnerjs.api.plugin.JSAPArgsParsingCommandPlugin.doCommand(JSAPArgsParsingCommandPlugin.java:86)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:430)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:26)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:18)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:435)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:126)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:104)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:70)
Caused by: java.lang.NullPointerException
	at org.bladerunnerjs.legacy.conf.TestRunnerConfiguration.addDefaultBrowserIfNoBrowserDefinedInArgumentsAndArgumentDoesntAskForNone(TestRunnerConfiguration.java:162)
	at org.bladerunnerjs.legacy.conf.TestRunnerConfiguration.getBrowsers(TestRunnerConfiguration.java:61)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.getBrowsers(TestRunner.java:126)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.<init>(TestRunner.java:99)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:72)
	... 10 more

org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error parsing test runner configuration file '/home/mvanko/Projects/salestrader/conf/test-runner.conf'.; null
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:76)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:59)
	at org.bladerunnerjs.api.plugin.JSAPArgsParsingCommandPlugin.doCommand(JSAPArgsParsingCommandPlugin.java:86)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:430)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:26)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:18)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:435)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:126)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:104)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:70)
Caused by: java.lang.NullPointerException
	at org.bladerunnerjs.legacy.conf.TestRunnerConfiguration.addDefaultBrowserIfNoBrowserDefinedInArgumentsAndArgumentDoesntAskForNone(TestRunnerConfiguration.java:162)
	at org.bladerunnerjs.legacy.conf.TestRunnerConfiguration.getBrowsers(TestRunnerConfiguration.java:61)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.getBrowsers(TestRunner.java:126)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.<init>(TestRunner.java:99)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:72)
	... 10 more
```

This doesn't happen on earlier versions and everything is running fine.

Running on a Linux - Fedora 22
AFAIK it is running fine on a windows machine

**Comment by thecapdan** [comment] 2016-01-04 10:23
Hi @michalvankodev 

I checked out your repo, and it looks like there was a change to your test-runner.conf on the 24th of November that may be causing this issue. There's a space missing in front of chrome definition for linux. Add a space and it should work. (maybe this change was accidental as it doesn't appear to have any relevance to the rest of that commit)

These conf files are susceptible to parsing errors if there's a single space out of place, plus the errors are rarely useful:)

Let me know if that works.

**Comment by michalvankodev** [comment] 2016-01-04 11:46
When I add a space I get a whole another error related to that space.
```
Caused By:
  Line 22, column 12: Error setting property 'browserPaths' on class: org.bladerunnerjs.legacy.conf.TestRunnerConfiguration

Stack Trace:
org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error parsing test runner configuration file '/home/mvanko/Projects/salestrader/conf/test-runner.conf'.; Line 22, column 12: Error setting property 'browserPaths' on class: org.bladerunnerjs.legacy.conf.TestRunnerConfiguration
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:76)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:59)
	at org.bladerunnerjs.api.plugin.JSAPArgsParsingCommandPlugin.doCommand(JSAPArgsParsingCommandPlugin.java:86)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:430)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:26)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:18)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:435)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:126)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:104)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:70)
Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 22, column 12: Error setting property 'browserPaths' on class: org.bladerunnerjs.legacy.conf.TestRunnerConfiguration
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:303)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:156)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:106)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:91)
	at org.bladerunnerjs.legacy.conf.TestRunnerConfiguration.getConfiguration(TestRunnerConfiguration.java:34)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.<init>(TestRunner.java:91)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:72)
	... 10 more
Caused by: com.esotericsoftware.yamlbeans.parser.Parser$ParserException: Line 22, column 12: Expected a 'block end' but found: block mapping start
	at com.esotericsoftware.yamlbeans.parser.Parser$26.produce(Parser.java:398)
	at com.esotericsoftware.yamlbeans.parser.Parser.getNextEvent(Parser.java:82)
	at com.esotericsoftware.yamlbeans.parser.Parser.peekNextEvent(Parser.java:93)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:274)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:156)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:299)
	... 16 more
```
Can someone else test it with Linux machine?

**Comment by thecapdan** [comment] 2016-01-04 11:52
Our linux dev should be in shortly... if not, I'll try on a VM.

Could you try reverting to your test-runner.conf to the version before November 24th and tell me if you get the same error? Was that change meant to be checked in?

**Comment by michalvankodev** [comment] 2016-01-04 11:58
Same error.

**Comment by thecapdan** [comment] 2016-01-04 12:57
I tried on a linux machine and I'm able to reproduce the error above with a test-runner.conf which used to work for us, so it looks like we have a regression at some point between 1.1 and 1.3. Which suggests our lead linux developer hasn't been running js tests locally:z

I'll move this onto our current backlog and see if we can get it fixed asap.

**Comment by dchambers** [comment] 2016-01-06 10:24
@thecapdan, what's the simplest way to reproduce this, is it just `gradle build`?

**Comment by thecapdan** [comment] 2016-01-06 10:27
@dchambers on a linux machine, gradle assemble followed by brjs test libs/javascript

**Comment by dchambers** [comment] 2016-01-06 10:28
:+1:

**Comment by dchambers** [comment] 2016-01-06 11:55
> @dchambers on a linux machine, gradle assemble followed by brjs test libs/javascript

@thecapdan, that works for me, and it must also work on Travis since it does a complete `gradle build`, which also runs those tests.

I'm using the `master` branch BTW, so maybe it's been fixed? How exactly did you reproduce this issue?

**Comment by thecapdan** [comment] 2016-01-06 11:58
i cloned ct, develop branch, gradle assemble followed by brjs test libs/javascript/ct-alerts

**Comment by dchambers** [comment] 2016-01-06 11:59
Okay, trying that now...

**Comment by dchambers** [comment] 2016-01-06 12:32
> i cloned ct, develop branch, gradle assemble followed by brjs test libs/javascript/ct-alerts. using a centos 5 machine

@thecapdan, this worked provided I ran `brjs test-server -b none` first and then manually connected a browser, but failed when I tried to run it without manually hooking up a browser with this error:

```
ERROR: java.io.IOException: incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.
Error:
  Error running tests.; incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.

Caused By:
  incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.

Stack Trace:
org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error running tests.; incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:126)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:54)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:428)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:34)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:433)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:119)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:123)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:71)
Caused by: java.io.IOException: incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.waitForServer(TestRunner.java:562)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.startBrowserProcesses(TestRunner.java:498)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.startServer(TestRunner.java:322)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runTests(TestRunner.java:157)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:121)
	... 9 more

org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error running tests.; incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:126)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:54)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:428)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:34)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:433)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:119)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:123)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:71)
Caused by: java.io.IOException: incorrect number of browser instances connected to the server: expected 1 but there were actually 0 instances connected.
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.waitForServer(TestRunner.java:562)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.startBrowserProcesses(TestRunner.java:498)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.startServer(TestRunner.java:322)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runTests(TestRunner.java:157)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:121)
	... 9 more
```

but this is only because the CT build doesn't support 64 Linux browsers (the BRJS build does), and is not the same as the errors you and have @michalvankodev have been seeing. I notice that you and  @michalvankodev are both running RedHat flavored Linux distros. Are these both 64 bit?

**Comment by thecapdan** [comment] 2016-01-06 14:02
CentOS release 5.11 (Final)
64bit

without starting the test server first, brjs test libs/javascript/ct-alerts results in:

org.bladerunnerjs.api.model.exception.command.CommandOperationException: Error parsing test runner configuration file '/space/home/build/workspace/temp/ct/ct-core/conf/test-runner.conf'.; null

So you can run the tests ok?

**Comment by dchambers** [comment] 2016-01-06 14:10
> So you can run the tests ok?

Yep. Travis can too, and if you're on 64 bit then it's not as a result of that, but something else. Which version of Java are you using @thecapdan, I'm using `1.7.0_80`.

**Comment by thecapdan** [comment] 2016-01-06 14:38
1.7.0_51

**Comment by dchambers** [comment] 2016-01-06 14:52
Won't be that then. I hate to say it, but I think as a CentosVM user you're perfectly placed to investigate this issue :-)

Only joking, I'll be in tomorrow and can grab a copy of your VM and take it from there.

**Comment by thecapdan** [comment] 2016-01-06 16:09
I think I see what's happened. We are unable to reproduce this issue in plain brjs since we are using a different version of test-runner.conf. 

@dchambers when you made changes to test-runner.conf to allow us run tests on travis, you made an additional section for linux64 https://github.com/BladeRunnerJS/brjs/commit/c49ed24e21cfce3fbfb2a1cd59bb9f03ac67178b#diff-10b9984ea19adc09ac8395f4c2f8ea6b

So I guess when we now run it on a 64 bit linux it requires a section in test-runner.conf called linux64, otherwise we get that horrible null error. When I add a linux64 section to the ct version of test-runner.conf, i no longer get that useless error :)

So, from brjs point of view we need to, in the very least, improve the error thrown in TestRunnerController when we don't have the appropriate section defined in test-runner.conf

**Comment by dchambers** [comment] 2016-01-06 16:59
Makes sense, though it's not obvious why I don't see this problem.

**Comment by thecapdan** [comment] 2016-01-06 17:54
@dchambers if you'd like to see the bug, in brjs-sdk/conf/test-runner.conf change "linux64" to "linux" and you should get the same exception as michal and I

**Comment by dchambers** [comment] 2016-01-07 03:19
> So, from brjs point of view we need to, in the very least, improve the error thrown in TestRunnerController when we don't have the appropriate section defined in test-runner.conf

Agreed, let's not close this till we provide an easy to comprehend error message.

**Comment by michalvankodev** [comment] 2016-01-07 09:10
> @michalvankodev would you mind adding a linux64 section to your test-runner.conf and see if that solves your problem?

This solved the problem for me. Thx!

**Comment by thecapdan** [comment] 2016-01-07 09:35
Excellent news. Thanks @michalvankodev 

I'll submit a fix today to ensure we throw a better exception message in the future

**Closed** 2016-01-11 09:51 UTC
Labels: 3 - Ready for Dev Review
